# Trilateral Filter Testing Notebook:

## Libraries:

In [5]:
import tensorflow_addons as tfa
import cv2
import numpy as np
import tensorflow as tf
from tensorflow import keras
from scipy import misc
import keras.backend as K
import tensorflow_addons as tfa
from tensorflow.python.keras.layers import Add, Conv2D, Input, Lambda, Dropout, Concatenate, Reshape, BatchNormalization, DepthwiseConv2D, MaxPooling2D


In [6]:
import os
from tensorflow.python.client import device_lib
# check GPU
def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']

In [528]:
get_available_gpus()
os.environ["CUDA_VISIBLE_DEVICES"] = "1,2,3"

## 28 Image Patterns:

In [15]:
# 28 Image Patterns
###########################################################################
def Pattern1():
    pattern = tf.constant(
        [
            [0, 0, 0, 0, 0, 1, 1], 
            [0, 0, 0, 0, 0, 1, 1], 
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1]
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern2():
    pattern = tf.constant(
        [
            [0, 0, 0, 0, 1, 1, 1], 
            [0, 0, 0, 0, 1, 1, 1], 
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1]
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern3():
    pattern = tf.constant(
        [
            [1, 1, 1, 0, 0, 0, 0], 
            [1, 1, 1, 0, 0, 0, 0], 
            [1, 1, 1, 0, 0, 0, 0], 
            [1, 1, 1, 0, 0, 0, 0], 
            [1, 1, 1, 0, 0, 0, 0], 
            [1, 1, 1, 0, 0, 0, 0], 
            [1, 1, 1, 0, 0, 0, 0] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern4():
    pattern = tf.constant(
        [
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 0, 0, 0, 0, 0]
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern5():
    pattern = tf.constant(
        [
            [1, 1, 1, 1, 1, 1, 1], 
            [1, 1, 1, 1, 1, 1, 1], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0]
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern6():
    pattern = tf.constant(
        [
            [1, 1, 1, 1, 1, 1, 1], 
            [1, 1, 1, 1, 1, 1, 1], 
            [1, 1, 1, 1, 1, 1, 1], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0]
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern7():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [1, 1, 1, 1, 1, 1, 1], 
            [1, 1, 1, 1, 1, 1, 1], 
            [1, 1, 1, 1, 1, 1, 1]
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern8():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [1, 1, 1, 1, 1, 1, 1], 
            [1, 1, 1, 1, 1, 1, 1]
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern9():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 1], 
            [0, 0, 0, 0, 0, 1, 1], 
            [0, 0, 0, 0, 1, 1, 1], 
            [0, 0, 0, 1, 1, 1, 1], 
            [0, 0, 1, 1, 1, 1, 1], 
            [0, 1, 1, 1, 1, 1, 1]
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern10():
    pattern = tf.constant(
        [ 
            [1, 1, 1, 1, 1, 1, 0],
            [1, 1, 1, 1, 1, 0, 0],
            [1, 1, 1, 1, 0, 0, 0],
            [1, 1, 1, 0, 0, 0, 0], 
            [1, 1, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern11():
    pattern = tf.constant(
        [ 
            [1, 1, 1, 1, 1, 0, 0],
            [1, 1, 1, 1, 0, 0, 0],
            [1, 1, 1, 0, 0, 0, 0], 
            [1, 1, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern12():
    pattern = tf.constant(
        [ 
            [1, 1, 1, 1, 0, 0, 0],
            [1, 1, 1, 0, 0, 0, 0], 
            [1, 1, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern13():
    pattern = tf.constant(
        [ 
            [0, 1, 1, 1, 1, 1, 1],
            [0, 0, 1, 1, 1, 1, 1], 
            [0, 0, 0, 1, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1], 
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 0, 1],
            [0, 0, 0, 0, 0, 0, 0] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern14():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 0, 0, 0, 0], 
            [1, 0, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 0, 0, 0], 
            [1, 1, 1, 1, 1, 0, 0],
            [1, 1, 1, 1, 1, 1, 0]
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern15():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0], 
            [1, 0, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 0, 0, 0], 
            [1, 1, 1, 1, 1, 0, 0]
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern16():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0], 
            [1, 0, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 0, 0, 0] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern17():
    pattern = tf.constant(
        [ 
            [0, 0, 1, 1, 1, 1, 1],
            [0, 0, 0, 1, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1], 
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 0, 1], 
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern18():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 1, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1], 
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 0, 1], 
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern19():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 1],
            [0, 0, 0, 0, 0, 1, 1], 
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 1, 1, 1, 1], 
            [0, 0, 1, 1, 1, 1, 1] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern20():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 1],
            [0, 0, 0, 0, 0, 1, 1], 
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 1, 1, 1, 1] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern21():
    pattern = tf.constant(
        [ 
            [1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 1, 1, 1], 
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern22():
    pattern = tf.constant(
        [ 
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1], 
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern23():
    pattern = tf.constant(
        [ 
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 0, 0, 0, 0], 
            [1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 0, 0, 0, 0] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern24():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1], 
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern25():
    pattern = tf.constant(
        [ 
            [1, 1, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern26():
    pattern = tf.constant(
        [ 
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1],
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1], 
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

def Pattern27():
    pattern = tf.constant(
        [ 
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0], 
            [1, 1, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0, 0] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern


def Pattern28():
    pattern = tf.constant(
        [ 
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1, 1], 
            [1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1] 
        ])
    #create the missing dims.
    pattern = tf.reshape(pattern, (1, 7, 7, 1))

    return pattern

In [16]:
def Patterns():
    image1=Pattern1()
    image2=Pattern2()
    image3=Pattern3()
    image4=Pattern4()
    image5=Pattern5()
    image6=Pattern6()
    image7=Pattern7()
    image8=Pattern8()
    image9=Pattern9()
    image10=Pattern10()
    image11=Pattern11()
    image12=Pattern12()
    image13=Pattern13()
    image14=Pattern14()
    image15=Pattern15()
    image16=Pattern16()
    image17=Pattern17()
    image18=Pattern18()
    image19=Pattern19()
    image20=Pattern20()
    image21=Pattern21()
    image22=Pattern22()
    image23=Pattern23()
    image24=Pattern24()
    image25=Pattern25()
    image26=Pattern26()
    image27=Pattern27()
    image28=Pattern28()
    Image_Patterns = Concatenate(axis=0)([image1, image2, image3, image4,
                                    image5, image6, image7, image8,
                                    image9, image10, image11, image12,
                                    image13, image14, image15, image16,
                                    image17, image18, image19, image20,
                                    image21, image22, image23, image24,
                                    image25, image26, image27, image28])
    return Image_Patterns

In [17]:
Pattern = Patterns()
print(Pattern.shape)

(28, 7, 7, 1)


# Triconvolution:

In [542]:
from time import perf_counter

# Tri-Convolution function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# input_matrix: g(*), depth_map_matrix: d(*), 
# width_filter: 2*M+1, height_filter: 2*N+1
###########################################################################

def triconvolution(input_matrix, depth_map_matrix):
    t1_start = perf_counter()
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # get the shape of input_matrix
    input_shape = input_matrix.shape
    K = input_shape[1]
    L = input_shape[2]
    # setup filter size
    width_filter = 7 
    height_filter = 7
    M = (width_filter-1)/2
    N = (height_filter-1)/2
    
    #########################################################
    # Setup Output matrix ###################################
    #########################################################
    #filtered_matrix = np.zeros(input_shape)
    filtered_matrix = tf.Variable(tf.zeros(input_shape, np.float32))
    print("Filtered_matrix size:", filtered_matrix.shape)
    output_shape = filtered_matrix.shape
    number_filtered_image = output_shape[0]
    width_filtered_image = output_shape[1]
    height_filtered_image = output_shape[2]
    
    #########################################################
    # convolution through trilateral_filter kernels
    #########################################################
    # iterate through the input image to get the output 
    # iterate through all output matrix in the batch
    for num in range(0, number_filtered_image):
        print("Number", num, " Picture:")
        # iterate through the output matrix width
        for m in range(0, width_filtered_image):
            # iterate thgouth the output matrix height
            for n in range(0, height_filtered_image):
                print("coordinate:", (m,n))
                # create a matrix for storing cropped image
                cropped_image = tf.Variable(tf.zeros((width_filter, height_filter), tf.float32))
                # create a matrix for storing cropped depth_matrix
                cropped_depth_matrix = tf.Variable(tf.zeros((width_filter, height_filter), tf.float32))
                # create a sub loop for loading cropped image
                # x index counter for cropped matrix and depth matrix
                k_cp = m-M
                for kn in range(0, width_filter):
                    # real width pointer for testing if the width index is inbound or not
                    # y index counter for cropped matrix and depth matrix
                    l_cp = n-N
                    for ln in range (0, height_filter):
                        #print("Cropped_image coordinate:", (k_cp, l_cp))
                        # real height pointer for testing if the height index is inbound or not
                        # if either k or l was out of bound
                        # store 0
                        if(k_cp < 0 or l_cp < 0):
                            index = [[kn, ln]]
                            #print("The size of the cropped image:", cropped_image.shape)
                            #print("The index put in:", index)
                            #print("The value put in:", [0.0])
                            assign1 = tf.tensor_scatter_nd_update(cropped_image, index, [0.0])
                            assign2 = tf.tensor_scatter_nd_update(cropped_depth_matrix, index,  [0.0])
                            l_cp += 1
                        # if both k and l were in bound
                        # store the matrix value in the cropped image and depth matrix
                        else:
                            k_cp=int(k_cp)
                            l_cp=int(l_cp)
                            index = [[kn, ln]]
                            #print("The size of the cropped image:", cropped_image.shape)
                            #print("The index put in:", index)
                            #print("The value put in:", input_matrix[num][k][l][0])
                            assign1 = tf.tensor_scatter_nd_update(cropped_image, index, [input_matrix[num][k_cp][l_cp][0]])
                            assign2 = tf.tensor_scatter_nd_update(cropped_depth_matrix, index, [depth_map_matrix[num][k_cp][l_cp][0]])
                            l_cp += 1
                    k_cp+=1
                # change the matrix to tensor
                cropped_image = tf.reshape(cropped_image, [1,7,7,1])
                cropped_depth_matrix = tf.reshape(cropped_depth_matrix, [1,7,7,1])
                # loop through the width of the filter
                # create a looping index for cropped width
                k = m-M
                for kn in range(0, width_filter):
                    # real width pointer for testing if the width inbound or not
                    # loop through the height of the filter
                    # create a looping index for cropped height
                    l = n-N
                    for ln in range (0, height_filter):
                        print("Now K and L:", (k,l))
                        # real height pointer for testing if the height index is inbound or nor
                        #print("Image corrdinate:", (k,l))
                        # if k or l was out of bound
                        # store filter
                        if (k < 0 or l < 0 or k > width_filtered_image or l > height_filtered_image):
                            value = [filtered_matrix[num][m][n][0] + 0.0]
                            index = [[num, m, n, 0]]
                            assign1 = tf.tensor_scatter_nd_update(filtered_matrix, index, value)
                            l += 1
                        else:
                            kn=int(kn)
                            ln=int(ln)
                            value = [filtered_matrix[num][m][n][0] + trilateral_filter(cropped_image, cropped_depth_matrix, num, m, n, kn, ln) * input_matrix[num][kn][ln][0]]
                            index = [[num, m, n, 0]]
                            assign1 = tf.tensor_scatter_nd_update(filtered_matrix, index, value)
                            l += 1
                    k+=1
                t1_stop = perf_counter()
                print("Elapsed time during the whole program in seconds:", t1_stop-t1_start) 
    
    # change it back to tesnor
    
    return filtered_matrix
                

In [479]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

imgL = cv2.imread(f'demo/L1.jpg',0)
imgR = cv2.imread(f'demo/R1.jpg',0)
stereo = cv2.StereoBM_create(numDisparities=96, blockSize=15)
disparity = stereo.compute(imgL,imgR)

In [312]:
print(disparity.shape)

(436, 1024)


In [543]:
img_tensor = tf.keras.preprocessing.image.img_to_array(imgL)
dep_tensor = tf.keras.preprocessing.image.img_to_array(disparity)

img_tensor = tf.constant(img_tensor, dtype=tf.float32)
dep_tensor = tf.constant(dep_tensor, dtype=tf.float32)


img_matrix = tf.reshape(img_tensor, [1,436,1024,1])
dep_matrix = tf.reshape(dep_tensor, [1,436,1024,1])


result = triconvolution(img_matrix, dep_matrix)

Filtered_matrix size: (1, 436, 1024, 1)
Number 0  Picture:
coordinate: (0, 0)
Now K and L: (-3.0, -3.0)
Now K and L: (-3.0, -2.0)
Now K and L: (-3.0, -1.0)
Now K and L: (-3.0, 0.0)
Now K and L: (-3.0, 1.0)
Now K and L: (-3.0, 2.0)
Now K and L: (-3.0, 3.0)
Now K and L: (-2.0, -3.0)
Now K and L: (-2.0, -2.0)
Now K and L: (-2.0, -1.0)
Now K and L: (-2.0, 0.0)
Now K and L: (-2.0, 1.0)
Now K and L: (-2.0, 2.0)
Now K and L: (-2.0, 3.0)
Now K and L: (-1.0, -3.0)
Now K and L: (-1.0, -2.0)
Now K and L: (-1.0, -1.0)
Now K and L: (-1.0, 0.0)
Now K and L: (-1.0, 1.0)
Now K and L: (-1.0, 2.0)
Now K and L: (-1.0, 3.0)
Now K and L: (0.0, -3.0)
Now K and L: (0.0, -2.0)
Now K and L: (0.0, -1.0)
Now K and L: (0.0, 0.0)
Elapsed time during the whole program in seconds: 3.1646671899361536
Elapsed time during the whole program in seconds: 3.172894316026941
Elapsed time during the whole program in seconds: 7.955699914949946
Now K and L: (0, 1)
Elapsed time during the whole program in seconds: 3.161306650959

InvalidArgumentError: slice index 7 of dimension 2 out of bounds. [Op:StridedSlice] name: strided_slice/

## Trilateral filter function:

In [440]:
# Trilateral filter function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# input_matrix: g(*), depth_map_matrix: d(*), 
# output_width_index: m (widht_filtered_image in triconvolution function),
# output_height_index: n (height_filtered_image in triconvolution function),
# filter_width_index: k (range from m-M in triconvolution function),
# filter_height_index: l (range from n-N to n+N in triconvlution function)
###########################################################################

def trilateral_filter(input_matrix, depth_map_matrix, number_filtered_image, output_width_index, output_height_index, filter_width_index, filter_height_index):
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # call out each filter involved in trilateral filter implementation
    output_trilateral_filter = domain_filter(output_width_index, output_height_index, filter_width_index, filter_height_index)*depth_filter(input_matrix, depth_map_matrix, number_filtered_image, output_width_index, output_height_index, filter_width_index, filter_height_index)*range_filter(input_matrix, depth_map_matrix, number_filtered_image, output_width_index, output_height_index, filter_width_index, filter_height_index)
    # multiply with normalization vector
    r = abs(output_trilateral_filter)
    output_trilateral_filter = r * output_trilateral_filter
    
    return output_trilateral_filter

In [303]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern1 = patterns[1]
pattern2 = patterns[2]
matrix = tf.constant([[0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1], 
                     [1, 1, 1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1, 1, 1]] , dtype=tf.float32)

dep_matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)


matrix = tf.reshape(matrix, [1,7,7,1])
dep_matrix = tf.reshape(dep_matrix, [1,7,7,1])




print(trilateral_filter(matrix, dep_matrix, 0, 1, 1, 1, 1))


bar:
tf.Tensor(
[[[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]], shape=(7, 7, 1), dtype=int32)
The first SAD:
tf.Tensor([33], shape=(1,), dtype=int32)
The second SAD:
tf.Tensor([16], shape=(1,), dtype=int32)
e_max: tf.Tensor(1.0, shape=(), dtype=float32)
e_min: tf.Tensor(0.0, shape=(), dtype=float32)
dd: tf.Tensor(-0.35714284, shape=(), dtype=float32)
dpm: 0.6666666666666666
bar:
tf.Tensor(
[[[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]], shape=(7, 7, 1), dtype=int32)
The fir

## Domain filter function (one of the three filters inside trilateral filter):

In [441]:
# Domain filter function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# output_width_index: m (widht_filtered_image in triconvolution function),
# output_height_index: n (height_filtered_image in triconvolution function),
# filter_width_index: k (range from m-M in triconvolution function),
# filter_height_index: l (range from n-N to n+N in triconvlution function)
###########################################################################

def domain_filter(output_width_index, output_height_index, filter_width_index, filter_height_index):
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # (m-k)^2
    coe1 = (output_width_index-filter_width_index) ** 2
    # (n-l)^2
    coe2 = (output_height_index- filter_height_index) ** 2
    # standard deviation s 
    stds = deviation_s()
    
    power_number = (-1)*(coe1+coe2)/(2*stds**2)
    output_domain_filter = math.exp(power_number)
    
    return output_domain_filter


# deviation_s function
###########################################################################

def deviation_s():
    output_standard_deviation_s = 1
    
    return output_standard_deviation_s

In [301]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern1 = patterns[1]
pattern2 = patterns[2]
matrix = tf.constant([[0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1], 
                     [1, 1, 1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1, 1, 1]] , dtype=tf.float32)

dep_matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)


matrix = tf.reshape(matrix, [1,7,7,1])
dep_matrix = tf.reshape(dep_matrix, [1,7,7,1])


print(domain_filter(1, 1, 1, 1))


1.0


## Depth filter function (one of the three filters inside trilateral filter):

In [442]:
# Depth filter function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# input_matrix: g(*), depth_map_matrix: d(*),
# number_filtered_image: (num in triconvolution function),
# output_width_index: m (widht_filtered_image in triconvolution function),
# output_height_index: n (height_filtered_image in triconvolution function),
# filter_width_index: k (range from m-M in triconvolution function),
# filter_height_index: l (range from n-N to n+N in triconvlution function)
###########################################################################

def depth_filter(input_matrix, depth_map_matrix, number_filtered_image, output_width_index, output_height_index, filter_width_index, filter_height_index):
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # (d(k,l)-d(m,n))
    coe1 = (depth_map_matrix[number_filtered_image, filter_width_index, filter_height_index,0] - depth_map_matrix[number_filtered_image, output_width_index, output_height_index,0])
    # e(m,n)
    # 28 Image Patterns
    Image_Patterns = Patterns()
    e = e_function(input_matrix, depth_map_matrix)
    # numerator part of power
    numer = (coe1 - e) ** 2
    # standard deviation d
    stdd = deviation_d(input_matrix, depth_map_matrix)
    # denominator part of power
    dener = 2*(stdd) ** 2
    
    power_number = (-1) * numer/dener 
    output_depth_filter = math.exp(power_number)
    
    return output_depth_filter

In [299]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern1 = patterns[1]
pattern2 = patterns[2]
matrix = tf.constant([[0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1], 
                     [1, 1, 1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1, 1, 1]] , dtype=tf.float32)

dep_matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)


matrix = tf.reshape(matrix, [1,7,7,1])
dep_matrix = tf.reshape(dep_matrix, [1,7,7,1])


print(depth_filter(matrix, dep_matrix, 0, 1, 1, 1, 1))


bar:
tf.Tensor(
[[[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]], shape=(7, 7, 1), dtype=int32)
The first SAD:
tf.Tensor([33], shape=(1,), dtype=int32)
The second SAD:
tf.Tensor([16], shape=(1,), dtype=int32)
e_max: tf.Tensor(1.0, shape=(), dtype=float32)
e_min: tf.Tensor(0.0, shape=(), dtype=float32)
dd: tf.Tensor(-0.35714284, shape=(), dtype=float32)
dpm: 0.6666666666666666
bar:
tf.Tensor(
[[[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]]], shape=(7, 7, 1), dtype=int32)
The fir

## Range filter function (one of the three filters inside trilateral filter):

In [522]:
from time import perf_counter

import math
# range filter function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# cropped_matrix(input_matrix): cropped_matrix, depth_map_matrix: cropped_dep_matrix,
# number_filtered_image: (num in triconvolution function),
# output_width_index: m (widht_filtered_image in triconvolution function),
# output_height_index: n (height_filtered_image in triconvolution function),
# filter_width_index: k (range from m-M in triconvolution function),
# filter_height_index: l (range from n-N to n+N in triconvlution function)
###########################################################################

def range_filter(input_matrix, depth_map_matrix, number_filtered_image, output_width_index, output_height_index, filter_width_index, filter_height_index):
    t1_start = perf_counter()
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # (g(k,l)-g(m,n))
    coe1 = (input_matrix[number_filtered_image, filter_width_index, filter_height_index,0] - input_matrix[number_filtered_image, output_width_index, output_height_index,0])
    # beta(m,n)
    # 28 Image Patterns
    beta = beta_function(input_matrix, depth_map_matrix)
    # numerator part of power
    numer = (coe1 - beta) ** 2
    # standard deviation d
    stdg = deviation_g(input_matrix, depth_map_matrix)
    # denominator part of power
    dener = 2*(stdg) ** 2
    
    power_number = (-1) * numer/dener 
    output_range_filter = math.exp(power_number)
    
    t1_stop = perf_counter()
    print("Elapsed time during the whole program in seconds:", t1_stop-t1_start) 
    return output_range_filter

In [523]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern1 = patterns[1]
pattern2 = patterns[2]
matrix = tf.constant([[0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1], 
                     [1, 1, 1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1, 1, 1]] , dtype=tf.float32)

dep_matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)


matrix = tf.reshape(matrix, [1,7,7,1])
dep_matrix = tf.reshape(dep_matrix, [1,7,7,1])


print(range_filter(matrix, dep_matrix, 0, 1, 1, 1, 1))


Elapsed time during the whole program in seconds: 7.979077798896469
0.60653062356059


## Standard deviation for d (Portion of depth filter function):

In [444]:
from statistics import stdev
def min_stdd():
    min_std = 0
    return min_std

In [445]:
from statistics import stdev
def max_stdd():
    # the most extreme situation that could happen in greyscale image
    data = (0,255)
    max_std = stdev(data)
    return max_std

In [526]:
from time import perf_counter

# deviation_d function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# Image_Patterns: 28 Image Patterns for Edge Matching 
# size: [28, 7, 7, 1], dtype: binary
# input_matrix: g(*), depth_map_matrix: d(*)
###########################################################################

def deviation_d(input_matrix, dep_map_matrix):
    t1_start = perf_counter()
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # setup the lower bound 
    min_std = min_stdd()
    # setup the upper bound
    max_std = max_stdd()
    # setup c2 value
    c2 = 1.7 # default value
    
    coe1 = min(max_std, c2*matching_distortion(input_matrix, dep_map_matrix))
    output_standard_deviation_d = max(min_std , coe1)
    t1_stop = perf_counter()
    print("Elapsed time during the whole program in seconds:", t1_stop-t1_start) 
    return output_standard_deviation_d

In [527]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern1 = patterns[1]
pattern2 = patterns[2]
matrix = tf.constant([[0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1], 
                     [1, 1, 1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1, 1, 1]] , dtype=tf.float32)

dep_matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)


matrix = tf.reshape(matrix, [1,7,7,1])
dep_matrix = tf.reshape(dep_matrix, [1,7,7,1])


print(deviation_d(matrix, dep_matrix))


Elapsed time during the whole program in seconds: 3.1740051199449226
1.1333333333333333


## Standard deviation for g (Portion of range filter function) (Passed Testing):

In [447]:
from statistics import stdev
def min_stdg():
    min_stdg = 0
    return min_stdg

In [448]:
from statistics import stdev
def max_stdg():
    # the most extreme situation that could happen in greyscale image
    data = (0,255)
    max_stdg = stdev(data)
    return max_stdg

In [524]:
from time import perf_counter

# deviation_g function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# Image_Patterns: 28 Image Patterns for Edge Matching 
# size: [28, 7, 7, 1], dtype: binary
# input_matrix: g(*), depth_map_matrix: d(*)
###########################################################################

def deviation_g(input_matrix, dep_map_matrix):
    t1_start = perf_counter()
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # setup the lower bound 
    min_std = min_stdg()
    # setup the upper bound
    max_std = max_stdg()
    # setup dpm
    dpm = matching_distortion(input_matrix, dep_map_matrix)
    # setup c2 value
    c2 = 1.0 # default value
    
    #print("min_std:", min_std)
    #print("max_std:", max_std)
    #print("dpm:", dpm)
    coe1 = min(max_std, c2*dpm)
    #print("coe1:", coe1)
    output_standard_deviation_g = max(min_std , coe1)
    
    t1_stop = perf_counter()
    print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return output_standard_deviation_g

In [525]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern1 = patterns[1]
pattern2 = patterns[2]
matrix = tf.constant([[0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1], 
                     [1, 1, 1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1, 1, 1]] , dtype=tf.float32)

dep_matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)


matrix = tf.reshape(matrix, [1,7,7,1])
dep_matrix = tf.reshape(dep_matrix, [1,7,7,1])


print(deviation_g(matrix, dep_matrix))


Elapsed time during the whole program in seconds: 3.1755171669647098
0.6666666666666666


## Matching distortion function (dpm) (Passed Testing):

In [450]:
def bar(pattern):
#     # just create a sample matrix based on pattern size
    input_shape = pattern.shape
    sub = tf.ones(input_shape, dtype = tf.int32)
    
    n_pattern = pattern
    n_pattern = tf.math.subtract(n_pattern,sub)
    n_pattern = tf.math.abs(n_pattern)
    
    out_matrix = n_pattern
    
    return out_matrix

In [472]:
from time import perf_counter

# matching_distortion function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# Image_Patterns: 28 Image Patterns for Edge Matching 
# size: [28, 7, 7, 1], dtype: binary
# input_matrix: g(*), depth_map_matrix: d(*)
###########################################################################

def matching_distortion(input_matrix, dep_map_matrix):
    #t1_start = perf_counter()
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # dmax
    dmax = 24
    # min (SAD (P_Ig, P_Id), SAD (P_Ig, bar_P_Id)
    
    P_ig = Best_Index(input_matrix)
    P_id = Best_Index(dep_map_matrix)
    P_idb = bar(P_id)
    P_idb = tf.reshape(P_idb, P_id.shape)
    
    #print("bar:")
    #print(P_idb)
    #print("The first SAD:")
    #print(SAD(P_ig, P_id))
    #print("The second SAD:")
    #print(SAD(P_ig, P_idb))
    
    coe1 = min(SAD(P_ig, P_id), 
               SAD(P_ig, P_idb))
    coe1 = coe1.numpy()
    dpm = (1/dmax)*coe1[0]
    
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return dpm

In [471]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()

matrix = tf.constant([[0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1], 
                     [1, 1, 1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1, 1, 1]] , dtype=tf.float32)

dep_matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)


matrix = tf.reshape(matrix, [1,7,7,1])
dep_matrix = tf.reshape(dep_matrix, [1,7,7,1])


print(matching_distortion(matrix, dep_matrix))


Elapsed time during the whole program in seconds: 3.1752634909935296
0.6666666666666666


## e function (Portion of depth filter function) (Passed Testing):

In [452]:
from time import perf_counter

# e function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# Image_Patterns: 28 Image Patterns for Edge Matching 
# size: [28, 7, 7, 1], dtype: binary
# input_matrix: g(*), depth_map_matrix: d(*)
###########################################################################

def e_function(cropped_matrix, dep_map_matrix):
    #t1_start = perf_counter()
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # dg
    P_id = Best_Index(dep_map_matrix)
    dd = dd_function(cropped_matrix, P_id)
    # dpm
    dpm = matching_distortion(cropped_matrix, dep_map_matrix)
    # e_min
    e_min = e_min_function(dep_map_matrix)
    # e_max
    e_max = e_max_function(dep_map_matrix)
    
    c4 = 300
    #print("e_max:", e_max)
    #print("e_min:", e_min)
    #print("dd:", dd)
    #print("dpm:", dpm)
    out_e = max(e_min, min(e_max, c4* dd/(1.5*dpm+0.5)))
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return out_e

In [418]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern1 = patterns[1]
pattern2 = patterns[2]
matrix = tf.constant([[0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1], 
                     [1, 1, 1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1, 1, 1]] , dtype=tf.float32)

dep_matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)


matrix = tf.reshape(matrix, [1,7,7,1])
dep_matrix = tf.reshape(dep_matrix, [1,7,7,1])


print(e_function(matrix, dep_matrix))


(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.05685026501305401
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.05655544891487807
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.05646978795994073
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.05645327200181782
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.05490702507086098
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.0560151970712468
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.056148977018892765
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.05683365894947201
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.05608732905238867
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.05626338708680123
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.05528929992578924
(1, 7, 7, 1)
Elapsed time during the whole program in seconds: 0.055979356984607875
(1,

## dd function (Portion of e function) (Passed Testing):

In [453]:
from time import perf_counter

def dd_function(cropped_matrix, Pattern):
    #t1_start = perf_counter()
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # dd
    out_dd = mean_block(cropped_matrix, Pattern, 1)-mean_block(cropped_matrix, Pattern, 0)
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return out_dd

In [387]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern = patterns[1]
matrix = tf.constant([[1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0]], dtype=tf.float32)

matrix = tf.reshape(matrix, [1,7,7,1])

print(dd_function(matrix, pattern))


Elapsed time during the whole program in seconds: 0.02713956101797521
tf.Tensor(-1.0, shape=(), dtype=float32)


## e minimum function (Portion of e function) (Passed Testing):

In [454]:
from time import perf_counter

# e_min_function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# cropped_matrix: matrix being matched
###########################################################################

def e_min_function(cropped_matrix):
    #t1_start = perf_counter()
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    shape = cropped_matrix.shape
    center_width = shape[1]/2
    center_height = shape[2]/2
                    
    minimum = tf.reduce_min(cropped_matrix)-cropped_matrix[0][round(center_width)-1][round(center_height)-1][0]
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return minimum

In [385]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

matrix = tf.constant([[-100, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)

print(matrix)


matrix = tf.reshape(matrix, [1,7,7,1])

print(e_min_function(matrix))


tf.Tensor(
[[-100.    1.    1.    0.    0.    0.    0.]
 [   1.    1.    1.    0.    0.    0.    0.]
 [   1.    1.    1.    0.    0.    0.    0.]
 [   1.    1.    1.    0.    0.    0.    0.]
 [   1.    1.    1.    0.    0.    0.    0.]
 [   1.    1.    1.    0.    0.    0.    0.]
 [   1.    1.    1.    0.    0.    0.    0.]], shape=(7, 7), dtype=float32)
Elapsed time during the whole program in seconds: 0.0007223489228636026
tf.Tensor(-100.0, shape=(), dtype=float32)


## e maximum function (Portion of e function) (Passed Testing):

In [455]:
from time import perf_counter

# e_max_function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# cropped_matrix: matrix being matched
###########################################################################

def e_max_function(cropped_matrix):
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    #t1_start = perf_counter()

    shape = cropped_matrix.shape
    center_width = shape[1]/2
    center_height = shape[2]/2

    maximum = tf.reduce_max(cropped_matrix)-cropped_matrix[0][round(center_width)-1][round(center_height)-1][0]
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return maximum

In [383]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 200, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)

print(matrix)


matrix = tf.reshape(matrix, [1,7,7,1])

print(e_max_function(matrix))


tf.Tensor(
[[  1.   1.   1.   0.   0.   0.   0.]
 [  1.   1.   1.   0.   0.   0.   0.]
 [  1.   1.   1.   0.   0.   0.   0.]
 [  1.   1.   1. 200.   0.   0.   0.]
 [  1.   1.   1.   0.   0.   0.   0.]
 [  1.   1.   1.   0.   0.   0.   0.]
 [  1.   1.   1.   0.   0.   0.   0.]], shape=(7, 7), dtype=float32)
Elapsed time during the whole program in seconds: 0.00083755305968225
tf.Tensor(0.0, shape=(), dtype=float32)


## beta function (Portion of range filter function) (Passed Testing):

In [516]:
from time import perf_counter

# beta function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# cropped_matrix: matrix being matched
# cropped_dep_map_matrix: depth map being matched
# Image_Patterns: 28 Image Patterns for Edge Matching 
# size: [28, 7, 7, 1], dtype: binary
# input_matrix: g(*), depth_map_matrix: d(*)
###########################################################################

def beta_function(cropped_matrix, cropped_dep_map_matrix):
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # dg
    #t1_start = perf_counter()
    
    Pattern = Best_Index(cropped_matrix)
    dg = dg_function(cropped_matrix, Pattern)
    # dpm
    dpm = matching_distortion(cropped_matrix, cropped_dep_map_matrix)
    # beta_min
    beta_min = beta_min_function(cropped_matrix)
    # beta_max
    beta_max = beta_max_function(cropped_matrix)
    
    c3 = 1.0
    
    #print("dg:", dg)
    #print("dpm:", dpm)
    out_beta = max(beta_min, min(beta_max, c3* dg/(1.5*dpm+0.5)))
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return out_beta

In [486]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern1 = patterns[1]
pattern2 = patterns[2]
matrix = tf.constant([[0, 1, 2, 3, 4, 5, 6],
                      [10, 11, 12, 13, 14, 15, 16],
                      [20, 21, 22, 23, 24, 25, 26],
                      [30, 31, 32, 33, 34, 35, 36],
                      [40, 41, 42, 43, 44, 45, 46],
                      [50, 51, 52, 53, 54, 55, 56],
                      [60, 61, 62, 63, 64, 65, 66]], dtype=tf.float32)

dep_matrix = tf.constant([[20, 13, 42, 73, 84, 55, 61],
                      [10, 11, 22, 53, 14, 50, 76],
                      [20, 29, 22, 23, 24, 25, 26],
                      [30, 36, 32, 33, 34, 35, 36],
                      [48, 47, 42, 47, 40, 45, 46],
                      [59, 59, 58, 53, 51, 51, 56],
                      [64, 62, 90, 63, 69, 62, 66]], dtype=tf.float32)

print(matrix)


matrix = tf.reshape(matrix, [1,7,7,1])

dep_matrix = tf.reshape(dep_matrix, [1,7,7,1])

print(beta_function(matrix, dep_matrix))


tf.Tensor(
[[ 0.  1.  2.  3.  4.  5.  6.]
 [10. 11. 12. 13. 14. 15. 16.]
 [20. 21. 22. 23. 24. 25. 26.]
 [30. 31. 32. 33. 34. 35. 36.]
 [40. 41. 42. 43. 44. 45. 46.]
 [50. 51. 52. 53. 54. 55. 56.]
 [60. 61. 62. 63. 64. 65. 66.]], shape=(7, 7), dtype=float32)
Elapsed time during the whole program in seconds: 4.825276731047779
tf.Tensor(-25.454546, shape=(), dtype=float32)


## dg function (Portion of beta function)(Passed Testing):

In [457]:
from time import perf_counter

def dg_function(cropped_matrix, Pattern):
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    # dg
    #t1_start = perf_counter() 
    out_dg = mean_block(cropped_matrix, Pattern, 1)-mean_block(cropped_matrix, Pattern, 0)
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return out_dg

In [373]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern = patterns[1]
matrix = tf.constant([[1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0]], dtype=tf.float32)

matrix = tf.reshape(matrix, [1,7,7,1])

print(dg_function(matrix, pattern))


Elapsed time during the whole program in seconds: 0.027012109057977796
tf.Tensor(-1.0, shape=(), dtype=float32)


## beta minimum function (Portion of beta function) (Passed Testing):

In [458]:
from time import perf_counter
# beta_min_function
###########################################################################
# Parameters from triconvolution function
###########################################################################

###########################################################################

def beta_min_function(cropped_matrix):
    #t1_start = perf_counter() 
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    shape = cropped_matrix.shape
    center_width = shape[1]/2
    center_height = shape[2]/2

    minimum = tf.reduce_min(cropped_matrix)-cropped_matrix[0][round(center_width)-1][round(center_height)-1][0]
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return minimum

In [371]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 500, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)


print(tf.reduce_min(matrix))


matrix = tf.reshape(matrix, [1,7,7,1])

print(beta_min_function(matrix))


tf.Tensor(0.0, shape=(), dtype=float32)
Elapsed time during the whole program in seconds: 0.0008392540039494634
tf.Tensor(-500.0, shape=(), dtype=float32)


## beta maximum function (Portion of beta function) (Passed Testing):

In [459]:
from time import perf_counter

# beta_max_function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# cropped_matrix: matrix being matched
###########################################################################

def beta_max_function(cropped_matrix):
    #t1_start = perf_counter() 
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    shape = cropped_matrix.shape
    center_width = shape[1]/2
    center_height = shape[2]/2

    maximum = tf.reduce_max(cropped_matrix)-cropped_matrix[0][round(center_width)-1][round(center_height)-1][0]
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return maximum

In [369]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 5, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)

print(matrix)


matrix = tf.reshape(matrix, [1,7,7,1])

print(beta_max_function(matrix))


tf.Tensor(
[[1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 5. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]], shape=(7, 7), dtype=float32)
Elapsed time during the whole program in seconds: 0.0007662109564989805
tf.Tensor(0.0, shape=(), dtype=float32)


## SAD function (Passed Testing):

In [460]:
from time import perf_counter

# SAD function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# Pattern 1: Image Pattern 1
# Pattern 2: Image Pattern 2
###########################################################################
def SAD(Pattern_1, Pattern_2):
    #t1_start = perf_counter() 
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    Shape = Pattern_1.shape
    output_SAD = 0
    for i in range (0, Shape[0]):
        for j in range (0, Shape[1]):
            output_SAD += abs(Pattern_1[i,j]-Pattern_2[i,j])
    
    
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return output_SAD

In [364]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern1 = patterns[0]
pattern2 = patterns[2]
matrix = tf.constant([[0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1],
                     [0, 0, 0, 0, 0, 1, 1], 
                     [1, 1, 1, 1, 1, 1, 1],
                     [1, 1, 1, 1, 1, 1, 1]] , dtype=tf.float32)

dep_matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0], 
                          [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)

matrix = tf.reshape(matrix, [7,7,1])
dep_matrix = tf.reshape(dep_matrix, [7,7,1])

print(SAD(matrix, dep_matrix))


Elapsed time during the whole program in seconds: 0.012471025926060975
tf.Tensor([33.], shape=(1,), dtype=float32)


## Best_Index function (Ig and Id) (Passed Testing):

In [540]:
from time import perf_counter

# Best_Index function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# cropped_matrix: matrix being matched
# Image_Patterns: 28 Image Patterns for Edge Matching 
# size: [28, 7, 7, 1], dtype: binary
###########################################################################

def Best_Index(cropped_matrix):
    #t1_start = perf_counter() 
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    Image_Patterns=Patterns()
    min_ej = 100000000000000000
    best_index = 1000
    
    for num in range(Image_Patterns.shape[0]):
        #print(num)
        test_ej = ej(cropped_matrix, Image_Patterns[num])
        if(test_ej < min_ej):
            #print("update!!")
            min_ej = test_ej
            best_index = num
        else:
            #print("No update!!")
            min_ej = min_ej
            best_index = best_index
                
    out_Best_Pattern = Image_Patterns[best_index]            
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return out_Best_Pattern

In [538]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern = patterns[1]
matrix = tf.constant([[1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0], 
                      [1, 1, 1, 0, 0, 0, 0]], dtype=tf.float32)

print(matrix)


matrix = tf.reshape(matrix, [1,7,7,1])

print(Best_Index(matrix))


tf.Tensor(
[[1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]], shape=(7, 7), dtype=float32)
Elapsed time during the whole program in seconds: 1.616820603958331
tf.Tensor(
[[[1]
  [1]
  [1]
  [0]
  [0]
  [0]
  [0]]

 [[1]
  [1]
  [1]
  [0]
  [0]
  [0]
  [0]]

 [[1]
  [1]
  [1]
  [0]
  [0]
  [0]
  [0]]

 [[1]
  [1]
  [1]
  [0]
  [0]
  [0]
  [0]]

 [[1]
  [1]
  [1]
  [0]
  [0]
  [0]
  [0]]

 [[1]
  [1]
  [1]
  [0]
  [0]
  [0]
  [0]]

 [[1]
  [1]
  [1]
  [0]
  [0]
  [0]
  [0]]], shape=(7, 7, 1), dtype=int32)


## ej function (portion of SAD function) (Passed Testing):

In [515]:
from time import perf_counter


# ej function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# cropped_matrix: matrix being matched
# Image_Patterns: 28 Image Patterns for Edge Matching 
# size: [28, 7, 7, 1], dtype: binary
###########################################################################

def ej(cropped_matrix, Pattern):
    #t1_start = perf_counter() 
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    sum_0 = 0
    sum_1 = 0
    shape = cropped_matrix.shape
    #print(shape)
    
    # get the two means
    m0 = mean_block(cropped_matrix, Pattern, 0)
    m1 = mean_block(cropped_matrix, Pattern, 1)
    
    #print("Input matrix:")
    #print(shape)
    for width in range(shape[1]):
        for height in range(shape[2]):
            if Pattern[width][height] == 0:
                # add to mean square error for 0
                #print((width,height), ":",cropped_matrix[0][width][height][0]) 
                amount = (cropped_matrix[0][width][height][0]-m0)**2
                sum_0 += amount
                #print("sum_0:", sum_0)
            elif Pattern[width][height] == 1:
                # add to mean square error for 1
                #print((width,height), ":",cropped_matrix[0][width][height][0]) 
                amount = (cropped_matrix[0][width][height][0]-m1)**2
                sum_1 += amount
                #print("sum_1:", sum_1)
            else:
                print("There's something wrong with the kernel")
    
    output_ej = sum_0 + sum_1
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    return output_ej

In [506]:
patterns = Patterns()
Pattern = patterns[1]
index_0 = tf.where(tf.equal(Pattern,0))
index_1 = tf.where(tf.equal(Pattern,1))
print(index_0[0])
print(index_1[0])

tf.Tensor([0 0 0], shape=(3,), dtype=int64)
tf.Tensor([0 4 0], shape=(3,), dtype=int64)


In [511]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern = patterns[1]
matrix = tf.constant([[1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0]], dtype=tf.float32)

print(matrix)


matrix = tf.reshape(matrix, [1,7,7,1])

print(ej(matrix, pattern))


tf.Tensor(
[[1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]], shape=(7, 7), dtype=float32)
Elapsed time during the whole program in seconds: 0.058166904957033694
tf.Tensor(0.0, shape=(), dtype=float32)


## Mean_block function (portion of ej function) (Passed Testing):

In [514]:
#from time import perf_counter

# mean_block function
###########################################################################
# Parameters from triconvolution function
###########################################################################
# cropped_matrix: matrix being matched
# Pattern: Image Pattern for Edge Matching
# k: 0 or 1 (which is used as the element for determining whether to perform the calculation or not)
###########################################################################

def mean_block(cropped_matrix, Pattern, k):
    #t1_start = perf_counter() 
    #########################################################
    # Setup Parameters ######################################
    #########################################################
    counter = 0
    sum_pixels = 0
    
    if k!=0 and k !=1:
        print("Wrong Implementation of ej_function")
    
    for width in range(cropped_matrix.shape[1]):
        for height in range(cropped_matrix.shape[2]):
            if (Pattern[width, height] == k):
                sum_pixels += cropped_matrix[0][width][height][0]
                counter += 1
    
    output_mean = sum_pixels / counter
    #t1_stop = perf_counter()
    #print("Elapsed time during the whole program in seconds:", t1_stop-t1_start)
    
    return output_mean

In [354]:
from PIL import Image
import numpy as np
import cv2
import tensorflow as tf

path = f'demo/1064.png'
image = Image.open(path)
img = np.array(image)

img_tensor = tf.keras.preprocessing.image.img_to_array(image)

# setup pattern 
patterns = Patterns()
pattern = patterns[1]
matrix = tf.constant([[1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0],
                      [1, 1, 1, 1, 0, 0, 0]], dtype=tf.float32)

matrix = tf.reshape(matrix, [1,7,7,1])

print(mean_block(matrix, pattern, 0))


Elapsed time during the whole program in seconds: 0.01537762291263789
tf.Tensor(1.0, shape=(), dtype=float32)
